# Generated by Django 4.0.4 on 2022-05-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classifierApp', '0004_apiresult'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiresult',
            old_name='imagepath',
            new_name='image',
        ),
    ]
