# Generated by Django 4.0.4 on 2022-05-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifierApp', '0006_result_imagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiresult',
            name='imagelink',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='apiresult',
            name='imagename',
            field=models.TextField(null=True),
        ),
    ]
